version: '3'

services:
  ci-build:
    image: harbor-bj.devopshub.cn/microsoft/aspnetcore-build:1.0-1.1
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./DemoAPP.sln && dotnet publish ./DemoAPP.sln -c Release -o ./obj/Docker/publish"
